# https://github.com/actions/labeler/blob/main/README.md

# When extending this, remember that in the PR, the labeler will run against
# the labeler.yml in master, more info:
# https://github.com/actions/labeler/issues/12
# This means your changes won't be tested. To test your branch, make a second
# branch with dummy changes, and open a PR on your own fork, against the
# first branch.

"manifest":
  - "west.yml"

"doc-required":
  - "doc/**/*"
  - "**/*.rst"

"CI-boot-dfu-test":
  - "include/bl*"
  - "include/fprotect.h"
  - "include/fw_info.*"
  - "include/mgmt/*"
  - "include/spm.h"
  - "include/dfu/**/*"
  - "include/net/**/*"
  - "cmake/*"
  - "modules/mcuboot/**/*"
  - "samples/nrf9160/*fota/**/*"
  - "samples/nrf9160/fmfu_smp_svr/**/*"
  - "samples/nrf9160/http_update/**/*"
  - "samples/nrf5340/netboot/*"
  - "samples/bootloader/**/*"
  - "scripts/bootloader/**/*"
  - "subsys/bootloader/**/*"
  - "subsys/nonsecure/*"
  - "subsys/partition_manager/*"
  - "subsys/dfu/*"
  - "subsys/fw_info/**/*"
  - "subsys/mgmt/**/*"
  - "subsys/pcd/*"
  - "subsys/spm/*"
  - "subsys/net/lib/*fota*/**/*"
  - "subsys/net/lib/download_client/**/*"
  - "tests/subsys/bootloader/**/*"
  - "tests/subsys/dfu/**/*"
  - "tests/subsys/fw_info/**/*"
  - "tests/subsys/net/**/*"

"CI-all-test":
  - "west.yml"
  - "**/*partition_manager*/**/*"
  - "**/*partition_manager*"

"CI-tfm-test":
  - "modules/tfm/**/*"
  - "samples/tfm/**/*"
  - "tests/subsys/spm/secure_services/**/*"

"CI-ble-test":
  - "subsys/bluetooth/**/*"
  - "include/bluetooth/**/*"
  - "samples/bluetooth/**/*"

"CI-mesh-test":
  - "subsys/bluetooth/mesh/**/*"
  - "include/bluetooth/mesh/**/*"
  - "tests/subsys/bluetooth/mesh/**/*"

"CI-zigbee-test":
  - "include/zigbee/**/*"
  - "samples/zigbee/**/*"
  - "subsys/dfu/**/*"
  - "subsys/mpsl/**/*"
  - "subsys/zigbee/**/*"
